### ISSUE TITLE
mettre les exemples en ligne

### ISSUE THREAD

**Issue by MAKIO135** [dsaadesignv/Dataviz-p5js#1]
En utilisant https://editor.p5js.org/ et ajouter les liens au readme.
Permettrait de les tester directement et les modifier en ligne  :)

**Comment by jbjoatton** [comment]
Ahah oui c'était prévu, d'autant que la plupart des sketches ont été créés dans l'éditeur de p5js
Merci pour les premiers ajouts, je complète le reste ;)

**Comment by MAKIO135** [comment]
Haha cool!
(On peut lancer nos ateliers mensuels à partir de Janvier! On en discute
bientôt)

Le mar. 20 nov. 2018 à 21:26, JB Joatton <notifications@github.com> a
écrit :
